#! /usr/bin/env python

from frame_poster.cli import entrypoint


def main():
    '''
    The main entry point for frame-poster CLI
    '''
    entrypoint()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit()
